ARG CUDA_VERSION=12.4.1

FROM nvidia/cuda:${CUDA_VERSION}-cudnn-devel-ubuntu22.04

RUN apt-get update && \
    apt-get -y install sudo python3.11 python3-pip && \
    pip3 install --upgrade pip

RUN pip3 install torch torchvision \
    --index-url https://download.pytorch.org/whl/cu128

RUN apt-get -y install git
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

ENV PYTHONPATH=$PYTHONPATH:/workdir
WORKDIR /workdir
