metadata:
  experiment_name: test
  date: 22-10-2025
  run_name: 33-a-amolf-beast
  description: model from 32.
  author: Nikolai Orlov
model:
  _target_: src.models.unet_skip_v2_metamodel.UNetMetaModel
  params:
    pretrain: /workdir/data/experiments/test_32-mac/model-327-0.748441.pth
    device: cuda:0
    nn_module:
      in_channels:
      - 1
      out_channels:
      - 1
    optimizer:
      lr: 0.5
train_params:
  max_epochs: 1000
  batch_size: 100
  early_stopping_epochs: 200
  reduce_lr_factor: 0.25
  reduce_lr_patience: 4
  monitor_metric: val_ssim
  monitor_metric_better: max
data:
  train:
  # - /workdir/data/samples/poly-ni/07-11-2023/poly-Ni_scan4_15kV_100pA_WD8-1_bin1_sat0150_ex280ms_gain00_gut00_step3500nm_2597points_.up2  # initial training
  - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan1_15kV_100pA_WD8-1_bin1_sat0110_exp140ms_gain00_gut00_step3500nm_4087points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan2_15kV_100pA_WD8-1_bin1_sat0110_exp140ms_gain00_gut00_step3500nm_2684points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan3_15kV_100pA_WD8-1_bin1_sat0110_exp140ms_gain00_gut00_step3500nm_2209points_scan1_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan4_15kV_100pA_WD8-1_bin1_sat0120_exp140ms_gain00_gut00_step3500nm_2205points_scan1_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan5_15kV_100pA_WD8-1_bin1_sat0100_exp140ms_gain00_gut00_step3500nm_2196points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan5_15kV_100pA_WD8-1_bin2_sat0200_exp140ms_gain00_gut00_step3500nm_2196points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan5_15kV_100pA_WD8-1_bin4_sat0270_exp140ms_gain00_gut00_step3500nm_2196points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan6_15kV_100pA_WD8-1_bin1_sat0100_exp140ms_gain00_gut00_step3500nm_2303points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan6_15kV_100pA_WD8-1_bin2_sat0220_exp140ms_gain00_gut00_step3500nm_2346points_.up2
  # - /workdir/data/samples/poly-ni/02-11-2023/poly-Ni_scan6_15kV_100pA_WD8-1_bin4_sat0270_exp140ms_gain00_gut00_step3500nm_2346points_.up2

  valid:
  # - /workdir/data/samples/poly-ni/07-11-2023/poly-Ni_scan4_15kV_100pA_WD8-1_bin1_sat0150_ex280ms_gain00_gut00_step3500nm_2597points_.up2  # initial training
  - /workdir/data/samples/poly-ni/07-11-2023/poly-Ni_scan3_15kV_100pA_WD8-1_bin1_sat0150_ex280ms_gain00_gut00_step3500nm_2318points_.up2  # validation dataset
  data_params:
    img_size: ${tuple:64,64}
    batch_size: 200
    num_workers: 0
    pin_memory: true
    gauss_sigma: 15.0
