metadata:
  experiment_name: test
  run_name: 001
  description: test train file
  author: Nikolai Orlov
model:
  _target_: src.models.unet_skip_v0_metamodel.UNetMetaModel
  params:
    pretrain: null
    device: cpu
    nn_module:
      n_channels:
      - 1
      o_channels:
      - 1
    optimizer:
      lr: 0.1
train_params:
  max_epochs: 100
  batch_size: 100
  early_stopping_epochs: 200
  reduce_lr_factor: 0.5
  reduce_lr_patience: 8
  monitor_metric: train_ssim
  monitor_metric_better: min
data:
  train:
  - /workdir/data/poly-Ni_scan6_15kV_100pA_WD8-1_bin1_sat0100_exp140ms_gain00_gut00_step3500nm_2303points_.up2
  
  valid:
  - /workdir/data/poly-Ni_scan6_15kV_100pA_WD8-1_bin1_sat0100_exp140ms_gain00_gut00_step3500nm_2303points_.up2
  
  data_params:
    img_size: ${tuple:128,128}
    batch_size: 2
    num_workers: 0
    pin_memory: true
    gauss_sigma: 15.0
