metadata:
  experiment_name: unet
  run_name: baseline
  description: 4x upscaling, MSE + windowed-SSIM loss

model:
  _target_: src.models.metamodel.UNetMetaModel
  params:
    pretrain: null
    device: cuda
    nn_module:
      n_channels: 1
      o_channels: 1
    optimizer:
      lr: 0.001

train_params:
  save_root: data/experiments
  max_epochs: 100
  early_stopping_epochs: 15
  reduce_lr_factor: 0.5
  reduce_lr_patience: 8
  monitor_metric: val_ssim
  monitor_metric_better: max

data:
  train:
    - data/scan_train.up2
  valid:
    - data/scan_valid.up2
  data_params:
    img_size: ${tuple:128,128}
    batch_size: 32
    num_workers: 0
    pin_memory: true
